# Site wide configuration

title: JBlogs
locale: en_US
description: Its my personal blogger. I write about Java, Gradle, mongodb and other technical stuff :)
logo: site-logo.png
search: true
url: https://jeetmp3.github.io

# Jekyll configuration

permalink:   /:categories/:year/:month/:day/:title
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

paginate: 5

# Site owner
owner:
  name: Jitendra Singh
  avatar: bio-photo.jpg
  email: jeet.mp3@gmail.com
  contact-number: +91-9990446178
  disqus-shortname: jeet_mp3
  twitter: JitendraBisht3
  facebook: 100001590673679
  github: jeetmp3
  stackexchange: http://stackoverflow.com/users/1739365/jitendra
  linkedin: jitendra-bisht-a7a25845
  instagram: jeet.mp3
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: JITTUBISHT
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
